# Generated by Django 5.0.14 on 2026-08-08 16:47

import django.core.validators
import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد ملک')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('transaction_type', models.CharField(choices=[('SALE', 'فروش'), ('PRESALE', 'پیش\u200cخرید'), ('RENT', 'اجاره'), ('MORTGAGE', 'رهن کامل')], max_length=10)),
                ('property_kind', models.CharField(choices=[('APARTMENT', 'آپارتمان مسکونی'), ('VILLA', 'ویلایی'), ('OFFICE', 'اداری'), ('COMMERCIAL', 'تجاری'), ('LAND', 'زمین'), ('OTHER', 'سایر')], max_length=15, verbose_name='نوع ملک')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('RESERVED', 'رزرو شده'), ('CLOSED', 'معامله\u200cشده'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=10)),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='منطقه/محله')),
                ('full_address', models.TextField(blank=True, verbose_name='آدرس کامل')),
                ('map_link', models.URLField(blank=True, verbose_name='لینک موقعیت روی نقشه')),
                ('area_sqm', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ زیربنا (متر)')),
                ('land_area_sqm', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ زمین (متر)')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب')),
                ('build_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل طبقات ساختمان')),
                ('unit_floor', models.SmallIntegerField(blank=True, null=True, verbose_name='طبقه واحد')),
                ('units_per_floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد واحد در طبقه')),
                ('direction', models.CharField(blank=True, max_length=50, verbose_name='جهت ساختمان')),
                ('document_type', models.CharField(blank=True, choices=[('SINGLE_PAGE', 'تک برگ'), ('TASSELED', 'منگوله\u200cدار'), ('AGREEMENT', 'قولنامه\u200cای'), ('OTHER', 'سایر')], max_length=15)),
                ('has_elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('parking_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پارکینگ')),
                ('has_storage', models.BooleanField(default=False, verbose_name='انباری')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('amenities', models.CharField(blank=True, help_text='با کاما جدا کنید', max_length=500, verbose_name='امکانات رفاهی')),
                ('heating_system', models.CharField(blank=True, max_length=100, verbose_name='سیستم گرمایش')),
                ('cooling_system', models.CharField(blank=True, max_length=100, verbose_name='سیستم سرمایش')),
                ('floor_covering', models.CharField(blank=True, max_length=100, verbose_name='نوع کفپوش')),
                ('is_renovated', models.BooleanField(default=False, verbose_name='بازسازی شده')),
                ('unit_condition', models.CharField(blank=True, max_length=150, verbose_name='وضعیت واحد')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مالک')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='فایل انحصاری')),
                ('public_description', models.TextField(blank=True, verbose_name='توضیحات عمومی (نمایش به مشتری)')),
                ('private_note', models.TextField(blank=True, verbose_name='یادداشت خصوصی مشاور')),
                ('renewal_priority_flag', models.BooleanField(default=False, verbose_name='اولویت یک\u200cماهه (به\u200cزودی خالی می\u200cشود)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_agent', models.ForeignKey(help_text='مشاور یا مدیری که این فایل را ثبت کرده — کلید اصلی کنترل دسترسی.', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='مشاور ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'فایل ملکی',
                'verbose_name_plural': 'فایل\u200cهای ملکی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contract_price', models.BigIntegerField(verbose_name='قیمت کل قرارداد (تومان)')),
                ('builder_company', models.CharField(blank=True, max_length=200, verbose_name='شرکت/سازنده')),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد پیشرفت پروژه')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل تخمینی')),
                ('amount_paid', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت\u200cشده تاکنون')),
                ('amount_remaining', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ باقی\u200cمانده')),
                ('installment_terms', models.CharField(blank=True, max_length=255, verbose_name='شرایط اقساط باقی\u200cمانده')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='شماره قرارداد پیش\u200cفروش')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presale_detail', to='properties.property')),
            ],
            options={
                'verbose_name': 'جزئیات پیش\u200cخرید',
                'verbose_name_plural': 'جزئیات پیش\u200cخرید',
            },
        ),
        migrations.CreateModel(
            name='MortgageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(verbose_name='تاریخ شروع قرارداد')),
                ('contract_end_date', models.DateField(verbose_name='تاریخ پایان قرارداد')),
                ('current_tenant_name', models.CharField(blank=True, max_length=150, verbose_name='نام مستاجر فعلی')),
                ('current_tenant_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مستاجر فعلی')),
                ('renewal_status', models.CharField(choices=[('NOT_CHECKED', 'بررسی نشده'), ('WANTS_RENEWAL', 'تمایل به تمدید'), ('WANTS_TO_LEAVE', 'تمایل به تخلیه'), ('UNCLEAR', 'نامشخص / تماس مجدد لازم است'), ('RENEWED', 'تمدید نهایی شد')], default='NOT_CHECKED', max_length=20)),
                ('last_contact_result', models.CharField(blank=True, max_length=255, verbose_name='نتیجه آخرین تماس')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تماس بعدی')),
                ('deposit_amount', models.BigIntegerField(verbose_name='مبلغ رهن کامل (تومان)')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_detail', to='properties.property')),
            ],
            options={
                'verbose_name': 'جزئیات رهن کامل',
                'verbose_name_plural': 'جزئیات رهن کامل',
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), properties.models.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'تصویر فایل',
                'verbose_name_plural': 'تصاویر فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(verbose_name='تاریخ شروع قرارداد')),
                ('contract_end_date', models.DateField(verbose_name='تاریخ پایان قرارداد')),
                ('current_tenant_name', models.CharField(blank=True, max_length=150, verbose_name='نام مستاجر فعلی')),
                ('current_tenant_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مستاجر فعلی')),
                ('renewal_status', models.CharField(choices=[('NOT_CHECKED', 'بررسی نشده'), ('WANTS_RENEWAL', 'تمایل به تمدید'), ('WANTS_TO_LEAVE', 'تمایل به تخلیه'), ('UNCLEAR', 'نامشخص / تماس مجدد لازم است'), ('RENEWED', 'تمدید نهایی شد')], default='NOT_CHECKED', max_length=20)),
                ('last_contact_result', models.CharField(blank=True, max_length=255, verbose_name='نتیجه آخرین تماس')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تماس بعدی')),
                ('deposit_amount', models.BigIntegerField(verbose_name='مبلغ ودیعه/رهن (تومان)')),
                ('monthly_rent', models.BigIntegerField(verbose_name='مبلغ اجاره ماهانه (تومان)')),
                ('convertible_to_mortgage', models.BooleanField(default=False, verbose_name='قابل تبدیل رهن/اجاره')),
                ('yearly_increase_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد افزایش سالانه پیشنهادی')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_detail', to='properties.property')),
            ],
            options={
                'verbose_name': 'جزئیات اجاره',
                'verbose_name_plural': 'جزئیات اجاره',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(verbose_name='قیمت کل (تومان)')),
                ('price_per_sqm', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت هر متر (تومان)')),
                ('payment_terms', models.CharField(choices=[('CASH', 'نقد'), ('INSTALLMENT', 'اقساط')], default='CASH', max_length=15)),
                ('down_payment', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ پیش\u200cپرداخت')),
                ('is_exchangeable', models.BooleanField(default=False, verbose_name='قابل معاوضه')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='properties.property')),
            ],
            options={
                'verbose_name': 'جزئیات فروش',
                'verbose_name_plural': 'جزئیات فروش',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['transaction_type', 'status'], name='properties__transac_c41406_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district'], name='properties__city_bd502c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner_agent'], name='properties__owner_a_2c0b0a_idx'),
        ),
    ]
