# Generated by Django 5.0.14 on 2026-08-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('current_tenant_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_tenant_phone', models.CharField(blank=True, default='', max_length=32)),
                ('renewal_status', models.CharField(blank=True, default='UNCLEAR', max_length=32)),
                ('last_contact_result', models.TextField(blank=True, default='')),
                ('next_contact_date', models.DateField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='properties.property')),
            ],
        ),
    ]
