# Generated by Django 5.0.14 on 2026-08-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageasset',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصاویر ملک'},
        ),
        migrations.AddField(
            model_name='imageasset',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی (کاور)'),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=models.ImageField(upload_to='properties/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
    ]
