# Generated by Django 5.0.14 on 2026-08-12 11:25

import django.core.validators
import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_imageasset_options_imageasset_is_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام امکانات')),
            ],
            options={
                'verbose_name': 'امکانات رفاهی',
                'verbose_name_plural': 'امکانات رفاهی',
            },
        ),
        migrations.AlterModelOptions(
            name='imageasset',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'تصویر فایل', 'verbose_name_plural': 'تصاویر فایل\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__transac_c41406_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__city_bd502c_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__owner_a_2c0b0a_idx',
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='caption',
            field=models.CharField(blank=True, max_length=150, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=models.ImageField(upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), properties.models.validate_image_size], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='مشاور ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='property',
            name='renewal_priority_flag',
            field=models.BooleanField(default=False, verbose_name='اولویت یک\u200cماهه'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='امکانات رفاهی مرتبط'),
        ),
    ]
