# Generated by Django 5.0.14 on 2026-08-13 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_amenity_alter_imageasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagedetail',
            name='currency',
            field=models.CharField(choices=[('IRT', 'تومان'), ('IRR', 'ریال'), ('USD', 'دلار')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='presaledetail',
            name='currency',
            field=models.CharField(choices=[('IRT', 'تومان'), ('IRR', 'ریال'), ('USD', 'دلار')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='property',
            name='other_kind_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام نوع ملک (سایر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='rentdetail',
            name='currency',
            field=models.CharField(choices=[('IRT', 'تومان'), ('IRR', 'ریال'), ('USD', 'دلار')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='currency',
            field=models.CharField(choices=[('IRT', 'تومان'), ('IRR', 'ریال'), ('USD', 'دلار')], default='IRT', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='mortgagedetail',
            name='current_tenant_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس مستاجر فعلی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='کد ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='direction',
            field=models.CharField(blank=True, choices=[('NORTH', 'شمالی'), ('SOUTH', 'جنوبی'), ('EAST', 'شرقی'), ('WEST', 'غربی'), ('DOUBLESIDED', 'دو کله'), ('NABSH', 'نبش')], max_length=20, null=True, verbose_name='جهت ساختمان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس مالک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه واحد'),
        ),
        migrations.AlterField(
            model_name='rentdetail',
            name='current_tenant_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس مستاجر فعلی'),
        ),
    ]
